[package]
name = "test3_package_with_nested_deps"
version = "0.1.0"
edition = "2018"

[dependencies]
doc-comment = "0.3.1"
itertools = { git = "https://github.com/rust-itertools/itertools.git", rev = "98d3978" }
test2_package_with_shallow_deps = { path = "../test2_package_with_shallow_deps" }
