name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: 'always'
  RUSTFLAGS: '-D warnings'

jobs:
  test-stable:
    name: Test stable
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          # Linux
          - runs-on: ubuntu-latest
          # Windows
          - runs-on: windows-latest
          # MacOS
          - runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test -- --skip args::args_tests::update_config_test_color_choice::case_4 --skip test_package

# TODO: Address clippy
#  clippy:
#    name: Check that clippy is happy
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: dtolnay/rust-toolchain@1.73.0
#      with:
#        components: clippy
#    - run: cargo clippy --target x86_64-unknown-linux-gnu --all-features

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --all -- --check
